spring:
  profiles:
    active: prod
    # program arguments  >  VM options  >  Enviroment variables  >proties ??> yml??


logging:
  config: classpath:logback-weblog.xml

jwt:
  # 签发人
  issuer: tys
  # 秘钥
  secret: xYEJv9RX1gSpFXoQJOTYRuBSjSHZQ1sRtn7a3A7XY28+ZYcmBef/yjeDW9Iq3UE9+ATzIrxrbgHk12UFKwiY8w==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 10000000000000
#  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer